apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.205.10
  bindPort: 6443
---
apiServer:
  certSANs:
  - 192.168.205.10
  extraArgs:
    audit-log-path: /var/log/kube-apiserver-audit.log
    audit-log-maxage: "5"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
    audit-policy-file: /home/vagrant/audit-policy.yaml
    audit-dynamic-configuration: "true"
    authorization-mode: Node,RBAC
    feature-gates: "DynamicAuditing=true"
  timeoutForControlPlane: 4m0s
  extraVolumes:
    - name: audit-policy
      hostPath: /home/vagrant/audit-policy.yaml
      mountPath: /home/vagrant/audit-policy.yaml
      readOnly: true
    - name: log-file
      hostPath: /var/log
      mountPath: /var/log
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  podSubnet: 172.16.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
